### ISSUE TITLE
UBQ node balance requests fail

### ISSUE THREAD

**Issue by wbobeirne** [MyCryptoHQ/shepherd#52]
### Description of the Issue

When making a request to a UBIQ node for the balance, it returns:

```
{
  "jsonrpc": "2.0",
  "id": "44358767f9d66865e982a366e44fe746",
  "address": "0x079fe31ACC9B202B168A4a1bB49D608F05a278B6",
  "result": "0"
}
```

I think this is because of "address", it looks like [additionalProperties is set to false in validation](https://github.com/MyCryptoHQ/shepherd/blob/master/src/validators/index.ts#L10). Should that maybe be set to true? 

### Steps to Reproduce

Try connecting to the UBQ node on mycrypto and unlocking a wallet.

**Comment by wbobeirne** [comment]
Ignore me, this is in MyCrypto validation, not shepherd.

**Comment by wbobeirne** [comment]
Just kidding this is actually a shepherd issue, it fails in validation.

**Comment by HenryNguyen5** [comment]
My bad, i think this part of the code got edited by accident. Will revert
